In [1]:
ls

Untitled.ipynb          listings.csv            reviews 2.csv
calendar.csv            neighbourhoods.csv      reviews.csv
listings 2.csv          neighbourhoods.geojson

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
calendar = pd.read_csv('calendar.csv')
reviews_1 = pd.read_csv('reviews.csv')
reviews_2 = pd.read_csv('reviews_2.csv')
listings = pd.read_csv('listings.csv')
listings_2 = pd.read_csv('listings_2.csv')
neighborhoods = pd.read_csv('neighbourhoods.csv')

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [16]:
calendar.shape, reviews_1.shape, reviews_2.shape, listings.shape, listings_2.shape, neighborhoods.shape

((2981670, 7), (306085, 2), (306085, 6), (8169, 16), (8169, 106), (77, 2))

In [17]:
calendar.head(100)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1313847,2019-05-19,t,$60.00,$60.00,32,1125
1,2384,2019-05-19,f,$70.00,$70.00,2,89
2,2384,2019-05-20,f,$70.00,$70.00,2,89
3,2384,2019-05-21,f,$70.00,$70.00,2,89
4,2384,2019-05-22,f,$70.00,$70.00,2,89
5,2384,2019-05-23,f,$70.00,$70.00,2,89
6,2384,2019-05-24,f,$70.00,$70.00,2,89
7,2384,2019-05-25,f,$70.00,$70.00,2,89
8,2384,2019-05-26,f,$70.00,$70.00,2,89
9,2384,2019-05-27,f,$70.00,$70.00,2,89
10,2384,2019-05-28,t,$70.00,$70.00,2,89
11,2384,2019-05-29,t,$70.00,$70.00,2,89
12,2384,2019-05-30,t,$70.00,$70.00,2,89
13,2384,2019-05-31,t,$70.00,$70.00,2,89
14,2384,2019-06-01,f,$75.00,$75.00,2,89
15,2384,2019-06-02,f,$75.00,$75.00,2,89
16,2384,2019-06-03,t,$75.00,$75.00,2,89
17,2384,2019-06-04,t,$75.00,$75.00,2,89
18,2384,2019-06-05,t,$75.00,$75.00,2,89
19,2384,2019-06-06,t,$75.00,$75.00,2,89
20,2384,2019-06-07,f,$75.00,$75.00,2,89
21,2384,2019-06-08,f,$75.00,$75.00,2,89
22,2384,2019-06-09,t,$75.00,$75.00,2,89
23,2384,2019-06-10,t,$75.00,$75.00,2,89
24,2384,2019-06-11,t,$75.00,$75.00,2,89
25,2384,2019-06-12,t,$75.00,$75.00,2,89
26,2384,2019-06-13,t,$75.00,$75.00,2,89
27,2384,2019-06-14,f,$75.00,$75.00,2,89
28,2384,2019-06-15,f,$75.00,$75.00,2,89
29,2384,2019-06-16,t,$75.00,$75.00,2,89
30,2384,2019-06-17,t,$75.00,$75.00,2,89
31,2384,2019-06-18,t,$75.00,$75.00,2,89
32,2384,2019-06-19,t,$75.00,$75.00,2,89
33,2384,2019-06-20,t,$75.00,$75.00,2,89
34,2384,2019-06-21,t,$75.00,$75.00,2,89
35,2384,2019-06-22,t,$75.00,$75.00,2,89
36,2384,2019-06-23,t,$75.00,$75.00,2,89
37,2384,2019-06-24,t,$75.00,$75.00,2,89
38,2384,2019-06-25,t,$75.00,$75.00,2,89
39,2384,2019-06-26,t,$75.00,$75.00,2,89
40,2384,2019-06-27,f,$70.00,$70.00,2,89
41,2384,2019-06-28,f,$70.00,$70.00,2,89
42,2384,2019-06-29,f,$70.00,$70.00,2,89
43,2384,2019-06-30,f,$70.00,$70.00,2,89
44,2384,2019-07-01,f,$70.00,$70.00,2,89
45,2384,2019-07-02,f,$70.00,$70.00,2,89
46,2384,2019-07-03,t,$75.00,$75.00,2,89
47,2384,2019-07-04,t,$75.00,$75.00,2,89
48,2384,2019-07-05,t,$80.00,$80.00,2,89
49,2384,2019-07-06,t,$80.00,$80.00,2,89
50,2384,2019-07-07,t,$80.00,$80.00,2,89
51,2384,2019-07-08,t,$75.00,$75.00,2,89
52,2384,2019-07-09,t,$75.00,$75.00,2,89
53,2384,2019-07-10,t,$75.00,$75.00,2,89
54,2384,2019-07-11,t,$75.00,$75.00,2,89
55,2384,2019-07-12,t,$75.00,$75.00,2,89
56,2384,2019-07-13,t,$75.00,$75.00,2,89
57,2384,2019-07-14,t,$75.00,$75.00,2,89
58,2384,2019-07-15,t,$75.00,$75.00,2,89
59,2384,2019-07-16,t,$75.00,$75.00,2,89
60,2384,2019-07-17,t,$75.00,$75.00,2,89
61,2384,2019-07-18,t,$75.00,$75.00,2,89
62,2384,2019-07-19,t,$75.00,$75.00,2,89
63,2384,2019-07-20,t,$75.00,$75.00,2,89
64,2384,2019-07-21,t,$75.00,$75.00,2,89
65,2384,2019-07-22,t,$75.00,$75.00,2,89
66,2384,2019-07-23,t,$75.00,$75.00,2,89
67,2384,2019-07-24,t,$75.00,$75.00,2,89
68,2384,2019-07-25,t,$75.00,$75.00,2,89
69,2384,2019-07-26,t,$75.00,$75.00,2,89
70,2384,2019-07-27,t,$75.00,$75.00,2,89
71,2384,2019-07-28,t,$75.00,$75.00,2,89
72,2384,2019-07-29,t,$75.00,$75.00,2,89
73,2384,2019-07-30,t,$75.00,$75.00,2,89
74,2384,2019-07-31,t,$75.00,$75.00,2,89
75,2384,2019-08-01,t,$90.00,$90.00,2,89
76,2384,2019-08-02,t,$90.00,$90.00,2,89
77,2384,2019-08-03,t,$90.00,$90.00,2,89
78,2384,2019-08-04,t,$90.00,$90.00,2,89
79,2384,2019-08-05,f,$50.00,$50.00,2,89
80,2384,2019-08-06,f,$50.00,$50.00,2,89
81,2384,2019-08-07,f,$50.00,$50.00,2,89
82,2384,2019-08-08,f,$50.00,$50.00,2,89
83,2384,2019-08-09,t,$70.00,$70.00,2,89
84,2384,2019-08-10,t,$80.00,$80.00,2,89
85,2384,2019-08-11,t,$70.00,$70.00,2,89
86,2384,2019-08-12,f,$50.00,$50.00,2,89
87,2384,2019-08-13,f,$50.00,$50.00,2,89
88,2384,2019-08-14,f,$50.00,$50.00,2,89
89,2384,2019-08-15,f,$50.00,$50.00,2,89
90,2384,2019-08-16,t,$75.00,$75.00,2,89
91,2384,2019-08-17,t,$75.00,$75.00,2,89
92,2384,2019-08-18,t,$75.00,$75.00,2,89
93,2384,2019-08-19,f,$50.00,$50.00,2,89
94,2384,2019-08-20,f,$50.00,$50.00,2,89
95,2384,2019-08-21,f,$50.00,$50.00,2,89
96,2384,2019-08-22,f,$50.00,$50.00,2,89
97,2384,2019-08-23,t,$75.00,$75.00,2,89
98,2384,2019-08-24,t,$75.00,$75.00,2,89
99,2384,2019-08-25,t,$75.00,$75.00,2,89

In [18]:
calendar['listing_id'].nunique()

8169

In [19]:
reviews_1.head()

   listing_id        date
0        2384  2015-01-09
1        2384  2015-03-24
2        2384  2015-04-19
3        2384  2015-04-30
4        2384  2015-05-04

In [20]:
reviews_2.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2384,25218143,2015-01-09,14385014,Ivan,it's a wonderful trip experience. I didn't exc...
1,2384,28475392,2015-03-24,16241178,Namhaitou,This is my first trip using Airbnb. I was a li...
2,2384,30273263,2015-04-19,26101401,Patrick,The reservation was canceled 80 days before ar...
3,2384,30974202,2015-04-30,26247321,Cristina,Sólo puedo decir cosas buenas de Rebecca. La h...
4,2384,31363208,2015-05-04,31293837,SuJung,Rebecca was an absolutely wonderful host.\r\n\...

In [8]:
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,Hyde Park - Walk to UChicago/Metra to McCormic...,2613,Rebecca,NaN,Hyde Park,41.78886,-87.58671,Private room,50,2,149,2019-05-17,2.81,1,316
1,4505,We're back. 365 Great Reviews. 1 bad one.,5775,Craig & Kathleen,NaN,South Lawndale,41.85495,-87.69696,Entire home/apt,117,2,368,2019-05-05,2.96,1,310
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90289,-87.68182,Entire home/apt,80,2,338,2019-05-05,2.81,1,309
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,NaN,Lincoln Park,41.91769,-87.63788,Entire home/apt,150,4,35,2019-05-15,0.56,11,280
4,10610,3 Comforts of Cooperative Living,2140,Lois And Ed,NaN,Hyde Park,41.79708,-87.59195,Private room,35,2,38,2019-04-12,0.68,5,240

In [21]:
listings_2.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,20190519023000,2019-05-19,Hyde Park - Walk to UChicago/Metra to McCormic...,"Be the sole guest in a quiet, vintage, 2nd flo...","The private bedroom has a queen size bed, ches...","Be the sole guest in a quiet, vintage, 2nd flo...",none,My apartment is located one block from beautif...,The basement laundry room hours are 8:00am to ...,UNIVERSITY OF CHICAGO: Visiting academics and ...,You will have access to the entire apartment (...,I will greet you when you arrive and show you ...,1. Your booking is for ONE (1) person only. Yo...,NaN,NaN,https://a0.muscache.com/im/pictures/acf6b3c0-4...,NaN,2613,https://www.airbnb.com/users/show/2613,Rebecca,2008-08-29,"Chicago, Illinois, United States",My 2 bdrm apartment is a 2nd floor walk-up in ...,within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/user/8bb47...,https://a0.muscache.com/im/pictures/user/8bb47...,Hyde Park,1.0,1.0,"['email', 'phone', 'reviews', 'manual_offline'...",t,t,"Chicago, IL, United States",Hyde Park,Hyde Park,NaN,Chicago,IL,60637,Chicago,"Chicago, IL",US,United States,41.78886,-87.58671,t,Condominium,Private room,1,1.0,1.0,1.0,Real Bed,"{TV,Wifi,Kitchen,""Free street parking"",Heating...",NaN,$50.00,$350.00,NaN,$0.00,$15.00,1,$0.00,2,89,2,2,89,89,2.0,89.0,3 weeks ago,t,15,39,61,316,2019-05-19,149,31,2015-01-09,2019-05-17,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,R17000015609,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",f,f,strict_14_with_grace_period,f,f,1,0,1,0,2.81
1,4505,https://www.airbnb.com/rooms/4505,20190519023000,2019-05-19,We're back. 365 Great Reviews. 1 bad one.,"We took the winter off, made things nicer arou...","We travel a lot, we know what people need. We...","We took the winter off, made things nicer arou...",none,NaN,NaN,The CTA train station is 30 yards (27 meters) ...,We also have a huge yard. Use it (weather perm...,NaN,Don't sit around all day watching T.V. Don't h...,NaN,NaN,https://a0.muscache.com/im/pictures/15019798/7...,NaN,5775,https://www.airbnb.com/users/show/5775,Craig & Kathleen,2008-12-29,"Chicago, Illinois, United States",Incredibly creative(Kathleen) and stunningly a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/5775/profile_...,https://a0.muscache.com/im/users/5775/profile_...,Little Village,1.0,1.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Chicago, IL, United States",Little Village,South Lawndale,NaN,Chicago,IL,60608,Chicago,"Chicago, IL",US,United States,41.85495,-87.69696,t,Apartment,Entire home/apt,7,1.0,3.0,4.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$117.00,$925.00,NaN,$0.00,$35.00,2,$25.00,2,60,2,2,60,60,2.0,60.0,yesterday,t,10,25,46,310,2019-05-19,368,23,2009-03-06,2019-05-05,96.0,10.0,10.0,10.0,10.0,9.0,9.0,t,R19000037538,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,moderate,f,f,1,1,0,0,2.96
2,7126,https://www.airbnb.com/rooms/7126,20190519023000,2019-05-19,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhood.,This is a very small studio apartment with a ...,A very small studio in a wonderful neighborhoo...,none,"Ukrainian Village was just named ""Hottest Neig...",We really like our neighbors and want guests t...,We are 1/2 mile away from the el train stop (b...,"You will be in your own private, tiny apartmen...",My family lives in the building but we are not...,This is a tiny apartment and is only appropria...,NaN,NaN,https://a0.muscache.com/im/pictures/51073/16c8...,NaN,17928,https://www.airbnb.com/users/show/17928,Sarah,2009-05-19,"Chicago, Illinois, United States",We live in Chicago. We love to travel and see ...,within an hour,100%,NaN,f,https://a0.muscache.com/im/users/17928/profile...,https://a0.muscache.com/im/users/17928/profile...,Ukrainian Village,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,f,"Chicago, IL, United States",Ukrainian Village,West Town,NaN,Chicago,IL,60622,Chicago,"Chicago, IL",US,United States,41.90289,-87.68182,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,Futon,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",NaN,$80.00,$600.00,NaN,$0.00,$0.00,1,$0.00,2,60,2,2,60,60,2.0,60.0,yesterday,t,7,23,38,309,2019-05-19,338,51,2009-07-03,2019-05-05,92.0,10.0,9.0,10.0,10.0,10.0,10.0,t,R18000034991,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",f,f,moderate,f,f,1,1,0,0,2.81
3,9811,https://www.airbnb.com/rooms/9811,20190519023000,2019-05-19,Barbara's Hideaway - Old Town,One-bedroom hideaway tucked into Old Town step...,"This lovely one bedroom ""hideaway"" is located ...",One-bedroom hideaway tucked into Old Town step...,none,Chicago’s Old Town neighborhood is squeezed be...,Vacation rental tax of 21.4 required in additi...,"Public transit in Chicago is excellent, and al...",NaN,We're always here for our guests. We have an ...,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/37df1935-8...,NaN,33004,https://www.airbnb.com/users/show/33004,At Home Inn,2009-08-21,"Chicago, Illinois, United States","Hi, we're Bob and Liz Biddle, long time Chicag...",within an hour,89%,NaN,f,https://a0.muscache.com/im/pictures/e23d4143-c...,https://a0.muscache.com/im/pictures/e23d4143-c...,Old Town,11.0,11.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Chicago, IL, United States",Old Town,Lincoln Park,NaN,Chicago,IL,60614,Chicago,"Chicago, IL",US,United States,41.91769,-87.63788,t,Apartment,Entire home/apt,4,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$150.00,"$1,050.00","$3,400.00",NaN,$95.00,2,$25.00,4,60,4,4,60,60,4.0,60.0,2 days ago,t,2,3,9,280,2019-05-19,35,15,2014-04-15,2019-05-15,92.0,9.0,9.0,10.0,9.0,10.0,9.0,t,2079260,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,strict_14_with_grace_period,f,f,11,11,0,0,0.56
4,10610,https://www.airbnb.com/rooms/10610,20190519023000,2019-05-19,3 Comforts of Cooperative Living,The condo is the 2nd floor in a lovely 1912 3-...,Newly furnished with queen bed and the comfort...,The condo is the 2nd floor in a lovely 1912 3-...,none,It's a 10 minute walk from the lakefront bike ...,If you stay longer than 21 days you are expect...,It is a short walk to public transportation th...,Pantry has non-perishable food for use by hous...,I travel a lot for work so you may not see me ...,No smoking in the condo. I only rent to adult...,NaN,NaN,https://a0.muscache.com/im/pictures/51944609/8...,NaN,2140,https://www.airbnb.com/users/show/2140,Lois And Ed,2008-08-16,"Aurora, Illinois, United States",Outgoing people who love people and exploring ...,within an hour,93%,NaN,f,https://a0.muscache.com/im/pictures/a8ba9bee-c...,https://a0.muscache.com/im/pictures/a8ba9bee-c...,Hyde Park,5.0,5.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Chicago, IL, United States",Hyde Park,Hyde Park,NaN,Chicago,IL,60615,Chicago,"Chicago, IL",US,United States,41.79708,-87.59195,t,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$35.00,$235.00,$805.00,$200.00,$50.00,1,$10.00,2,365,2,2,365,365,2.0,365.0,yesterday,t,7,37,61,240,2019-05-19,38,9,2014-10-25,2019-04-12,85.0,9.0,8.0,9.0,9.0,10.0,9.0,t,City registration pending,"{""Illinois State"","" Cook County"","" IL"","" CHICA...",t,f,moderate,f,f,5,1,4,0,0.68

In [10]:
neighborhoods.head()

   neighbourhood_group   neighbourhood
0                  NaN     Albany Park
1                  NaN  Archer Heights
2                  NaN   Armour Square
3                  NaN         Ashburn
4                  NaN  Auburn Gresham

In [22]:
calendar.shape, reviews_1.shape, reviews_2.shape, listings.shape, listings_2.shape, neighborhoods.shape

((2981670, 7), (306085, 2), (306085, 6), (8169, 16), (8169, 106), (77, 2))

In [23]:
listings_2['id'].nunique()

8169

In [24]:
listings_2.nunique()

id                                              8169
listing_url                                     8169
scrape_id                                          1
last_scraped                                       1
name                                            8035
summary                                         7097
space                                           5701
description                                     7486
experiences_offered                                1
neighborhood_overview                           4600
notes                                           3612
transit                                         4787
access                                          4585
interaction                                     4267
house_rules                                     4449
thumbnail_url                                      0
medium_url                                         0
picture_url                                     7904
xl_picture_url                                     0
host_id                                         4615
host_url                                        4615
host_name                                       2226
host_since                                      2247
host_location                                    247
host_about                                      2936
host_response_time                                 4
host_response_rate                                54
host_acceptance_rate                               0
host_is_superhost                                  2
host_thumbnail_url                              4603
host_picture_url                                4603
host_neighbourhood                               117
host_listings_count                               55
host_total_listings_count                         55
host_verifications                               265
host_has_profile_pic                               2
host_identity_verified                             2
street                                            20
neighbourhood                                     87
neighbourhood_cleansed                            74
neighbourhood_group_cleansed                       0
city                                              16
state                                              3
zipcode                                           75
market                                             3
smart_location                                    20
country_code                                       1
country                                            1
latitude                                        6474
longitude                                       5989
is_location_exact                                  2
property_type                                     27
room_type                                          3
accommodates                                      20
bathrooms                                         19
bedrooms                                          15
beds                                              24
bed_type                                           5
amenities                                       7306
square_feet                                       34
price                                            432
weekly_price                                     211
monthly_price                                    220
security_deposit                                  73
cleaning_fee                                     172
guests_included                                   17
extra_people                                      62
minimum_nights                                    53
maximum_nights                                   136
minimum_minimum_nights                            54
maximum_minimum_nights                            74
minimum_maximum_nights                           136
maximum_maximum_nights                           146
minimum_nights_avg_ntm                           180
maximum_nights_avg_ntm                           225
calendar_updated                                  48
has_availability                                   1
availability_30                                   31
availability_60                                   61
availability_90                                   91
availability_365                                 366
calendar_last_scraped                              1
number_of_reviews                                319
number_of_reviews_ltm                            131
first_review                                    1607
last_review                                      663
review_scores_rating                              41
review_scores_accuracy                             8
review_scores_cleanliness                          9
review_scores_checkin                              8
review_scores_communication                        8
review_scores_location                             8
review_scores_value                                8
requires_license                                   2
license                                         3925
jurisdiction_names                                 7
instant_bookable                                   2
is_business_travel_ready                           1
cancellation_policy                                6
require_guest_profile_picture                      2
require_guest_phone_verification                   2
calculated_host_listings_count                    38
calculated_host_listings_count_entire_homes       33
calculated_host_listings_count_private_rooms      20
calculated_host_listings_count_shared_rooms       14
reviews_per_month                                822
dtype: int64

In [54]:
listings_2['reviews_per_month'].value_counts()

1.00     166
2.00      79
3.00      54
0.09      44
0.05      40
0.10      40
0.14      38
0.29      37
0.13      35
0.06      34
0.22      34
0.17      34
0.27      34
0.32      34
0.12      33
0.11      33
0.26      33
0.38      31
0.39      31
0.19      31
0.88      30
0.49      30
0.34      30
0.28      30
0.83      30
0.81      30
0.15      29
0.33      29
0.47      28
0.08      28
0.16      28
0.61      28
0.18      28
0.43      27
0.25      27
4.00      27
0.69      26
0.58      26
0.44      26
0.24      26
0.41      26
0.36      25
0.85      25
0.31      25
0.59      24
0.21      24
0.35      24
0.98      24
0.30      23
0.73      23
0.52      23
0.75      23
0.46      22
0.94      22
0.03      22
1.22      22
0.74      22
0.53      22
0.04      22
1.09      22
0.51      21
1.88      21
0.23      21
1.52      21
2.73      21
1.67      21
1.25      21
0.68      21
0.57      21
3.16      21
0.07      21
0.93      20
1.19      20
0.77      20
0.42      20
0.63      20
1.82      20
0.40      20
0.90      19
0.86      19
1.71      19
0.80      19
0.97      19
0.65      19
0.82      19
0.62      19
0.71      19
0.20      19
0.54      19
2.34      19
0.50      19
0.99      19
1.80      18
1.54      18
0.84      18
0.48      18
2.50      18
1.18      18
1.07      18
0.76      18
0.95      17
0.64      17
0.45      17
0.96      17
1.58      17
1.15      17
1.45      17
1.28      17
1.04      17
0.55      17
2.37      17
1.50      17
1.29      17
1.08      16
3.07      16
1.20      16
1.73      16
1.02      16
2.43      16
4.29      16
1.27      16
0.37      16
1.03      16
2.42      16
0.60      16
3.45      16
1.69      16
1.62      16
2.14      16
2.71      16
1.60      16
1.41      16
0.91      16
3.75      16
1.17      16
1.30      16
1.32      16
0.78      16
3.33      15
2.81      15
1.47      15
3.46      15
0.92      15
3.52      15
0.70      15
1.34      15
1.55      15
0.56      15
2.65      15
1.94      15
2.01      14
2.75      14
0.67      14
2.03      14
1.61      14
1.23      14
2.59      14
1.51      14
0.87      14
4.33      14
1.98      14
1.36      14
1.21      14
4.62      14
1.48      14
1.10      14
1.40      14
1.95      14
1.05      14
1.78      14
2.31      14
1.16      14
2.55      14
1.64      14
2.11      14
2.12      14
2.17      13
2.36      13
2.86      13
2.05      13
2.27      13
1.85      13
1.68      13
2.54      13
1.89      13
2.09      13
1.84      13
1.12      13
2.25      13
2.52      13
0.79      13
3.88      13
3.11      13
2.72      13
5.00      13
1.24      13
1.53      12
2.28      12
1.77      12
1.83      12
1.76      12
2.93      12
2.38      12
1.13      12
2.08      12
1.49      12
4.05      12
2.23      12
1.11      12
1.56      12
1.87      12
2.44      12
1.96      12
1.92      12
1.42      12
2.26      12
0.72      12
3.81      12
3.03      12
1.63      12
2.30      11
1.44      11
1.66      11
3.13      11
1.38      11
3.96      11
1.65      11
3.53      11
2.68      11
1.79      11
1.06      11
2.79      11
2.90      11
3.69      11
3.54      11
4.04      11
3.01      11
2.07      11
3.10      11
2.20      11
2.76      11
1.31      11
3.85      11
0.66      11
2.40      11
3.40      11
1.43      11
2.69      11
3.26      11
1.33      11
        ...
7.18       3
5.34       3
7.62       2
6.14       2
3.06       2
6.08       2
7.76       2
7.39       2
7.03       2
5.91       2
7.13       2
4.49       2
8.31       2
5.02       2
6.69       2
7.22       2
5.11       2
8.90       2
6.94       2
6.09       2
8.20       2
5.72       2
8.34       2
5.47       2
7.61       2
7.55       2
6.24       2
7.40       2
6.53       2
5.21       2
5.70       2
7.83       2
4.73       2
7.58       2
5.68       2
6.82       2
7.00       2
6.66       2
7.96       2
6.45       2
7.23       2
5.42       2
5.60       2
7.07       2
5.07       2
4.52       2
10.74      2
7.06       2
6.34       2
5.26       2
7.48       2
6.77       2
7.38       2
7.70       2
5.82       2
5.64       2
6.96       2
7.78       2
4.61       2
8.18       2
5.80       2
6.20       2
10.45      2
6.07       2
6.55       2
6.26       2
5.93       2
6.91       2
4.47       2
9.33       2
6.58       2
6.13       2
5.58       2
6.05       2
9.17       2
5.28       2
5.87       2
7.86       2
5.32       2
7.27       2
7.08       2
5.89       2
6.65       2
5.55       2
5.99       2
5.81       2
7.99       2
4.43       2
4.68       2
6.36       2
6.42       2
5.18       2
6.51       2
5.98       2
8.41       2
4.79       2
8.64       2
7.34       2
7.74       2
7.69       2
5.10       2
6.75       2
5.53       2
5.67       2
8.11       2
4.64       2
8.76       1
9.85       1
6.28       1
8.40       1
7.11       1
9.97       1
11.47      1
9.09       1
7.71       1
7.31       1
7.19       1
12.41      1
10.52      1
7.29       1
7.98       1
7.46       1
7.45       1
8.96       1
6.73       1
6.92       1
9.37       1
7.97       1
7.44       1
7.25       1
14.48      1
10.41      1
9.00       1
9.99       1
6.79       1
5.50       1
6.40       1
6.19       1
8.59       1
6.06       1
8.80       1
6.60       1
9.14       1
7.59       1
7.20       1
8.39       1
6.63       1
6.11       1
8.87       1
6.49       1
7.05       1
6.64       1
9.78       1
8.91       1
6.33       1
8.29       1
9.01       1
9.89       1
8.79       1
8.99       1
8.08       1
7.12       1
6.54       1
4.99       1
7.14       1
6.16       1
7.89       1
9.66       1
9.96       1
7.79       1
6.88       1
10.65      1
7.21       1
6.57       1
10.30      1
8.70       1
8.55       1
5.78       1
5.05       1
6.76       1
9.67       1
3.91       1
6.86       1
9.55       1
8.67       1
8.19       1
7.60       1
6.95       1
8.48       1
9.34       1
8.07       1
5.92       1
8.17       1
8.28       1
6.74       1
6.83       1
9.02       1
10.15      1
5.66       1
11.40      1
10.44      1
8.06       1
8.56       1
6.90       1
7.80       1
5.65       1
4.31       1
11.17      1
10.03      1
8.46       1
9.24       1
7.54       1
8.95       1
8.53       1
8.93       1
6.01       1
6.59       1
9.03       1
10.06      1
6.39       1
9.72       1
5.62       1
6.46       1
7.41       1
10.69      1
6.78       1
4.56       1
7.57       1
10.19      1
7.36       1
4.54       1
7.43       1
12.34      1
7.47       1
6.84       1
10.04      1
4.69       1
14.83      1
10.32      1
6.21       1
6.03       1
6.35       1
7.30       1
10.60      1
4.90       1
8.27       1
11.62      1
8.66       1
11.07      1
8.75       1
Name: reviews_per_month, Length: 822, dtype: int64

In [100]:
df = listings_2.drop([
'id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary', 'space', 'description', 'experiences_offered',
'neighborhood_overview', 'notes', 'transit', 'access', 'interaction', 'house_rules', 'thumbnail_url', 'medium_url',
'picture_url', 'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url', 'host_picture_url', 'street', 'state', 'market',
'smart_location', 'country', 'square_feet', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60',
'availability_90', 'availability_365', 'calendar_last_scraped', 'first_review', 'last_review', 'license', 'jurisdiction_names',
'is_business_travel_ready', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes',
'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'host_verifications', 'host_has_profile_pic',
'host_identity_verified', 'host_listings_count', 'host_total_listings_count', 'host_response_time', 'host_response_rate',
'host_is_superhost', 'neighbourhood_group_cleansed', 'city', 'country_code', 'is_location_exact', 'monthly_price', 'minimum_nights',
'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights',
'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'requires_license', 'require_guest_profile_picture', 'require_guest_phone_verification',
'weekly_price', 'host_neighbourhood'], axis=1)

In [101]:
df.head()

,neighbourhood,neighbourhood_cleansed,zipcode,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,security_deposit,cleaning_fee,guests_included,extra_people,number_of_reviews,number_of_reviews_ltm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,reviews_per_month
0,Hyde Park,Hyde Park,60637,41.78886,-87.58671,Condominium,Private room,1,1.0,1.0,1.0,Real Bed,"{TV,Wifi,Kitchen,""Free street parking"",Heating...",$50.00,$0.00,$15.00,1,$0.00,149,31,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,strict_14_with_grace_period,2.81
1,Little Village,South Lawndale,60608,41.85495,-87.69696,Apartment,Entire home/apt,7,1.0,3.0,4.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$117.00,$0.00,$35.00,2,$25.00,368,23,96.0,10.0,10.0,10.0,10.0,9.0,9.0,t,moderate,2.96
2,Ukrainian Village,West Town,60622,41.90289,-87.68182,Apartment,Entire home/apt,2,1.0,1.0,1.0,Futon,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",$80.00,$0.00,$0.00,1,$0.00,338,51,92.0,10.0,9.0,10.0,10.0,10.0,10.0,f,moderate,2.81
3,Old Town,Lincoln Park,60614,41.91769,-87.63788,Apartment,Entire home/apt,4,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$150.00,NaN,$95.00,2,$25.00,35,15,92.0,9.0,9.0,10.0,9.0,10.0,9.0,t,strict_14_with_grace_period,0.56
4,Hyde Park,Hyde Park,60615,41.79708,-87.59195,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$35.00,$200.00,$50.00,1,$10.00,38,9,85.0,9.0,8.0,9.0,9.0,10.0,9.0,t,moderate,0.68

In [102]:
df.columns

Index(['neighbourhood', 'neighbourhood_cleansed', 'zipcode', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'bed_type', 'amenities', 'price',
       'security_deposit', 'cleaning_fee', 'guests_included', 'extra_people',
       'number_of_reviews', 'number_of_reviews_ltm', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable',
       'cancellation_policy', 'reviews_per_month'],
      dtype='object')

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8169 entries, 0 to 8168
Data columns (total 30 columns):
neighbourhood                  8169 non-null object
neighbourhood_cleansed         8169 non-null object
zipcode                        8143 non-null object
latitude                       8169 non-null float64
longitude                      8169 non-null float64
property_type                  8169 non-null object
room_type                      8169 non-null object
accommodates                   8169 non-null int64
bathrooms                      8164 non-null float64
bedrooms                       8168 non-null float64
beds                           8167 non-null float64
bed_type                       8169 non-null object
amenities                      8169 non-null object
price                          8169 non-null object
security_deposit               5990 non-null object
cleaning_fee                   7089 non-null object
guests_included                8169 non-null int64
extra_people                   8169 non-null object
number_of_reviews              8169 non-null int64
number_of_reviews_ltm          8169 non-null int64
review_scores_rating           7018 non-null float64
review_scores_accuracy         7018 non-null float64
review_scores_cleanliness      7018 non-null float64
review_scores_checkin          7016 non-null float64
review_scores_communication    7016 non-null float64
review_scores_location         7016 non-null float64
review_scores_value            7016 non-null float64
instant_bookable               8169 non-null object
cancellation_policy            8169 non-null object
reviews_per_month              7084 non-null float64
dtypes: float64(13), int64(4), object(13)
memory usage: 1.9+ MB

In [104]:
df.nunique()

neighbourhood                    87
neighbourhood_cleansed           74
zipcode                          75
latitude                       6474
longitude                      5989
property_type                    27
room_type                         3
accommodates                     20
bathrooms                        19
bedrooms                         15
beds                             24
bed_type                          5
amenities                      7306
price                           432
security_deposit                 73
cleaning_fee                    172
guests_included                  17
extra_people                     62
number_of_reviews               319
number_of_reviews_ltm           131
review_scores_rating             41
review_scores_accuracy            8
review_scores_cleanliness         9
review_scores_checkin             8
review_scores_communication       8
review_scores_location            8
review_scores_value               8
instant_bookable                  2
cancellation_policy               6
reviews_per_month               822
dtype: int64

In [105]:
df['number_of_reviews']

0       149
1       368
2       338
3        35
4        38
5         9
6         4
7         9
8        37
9       178
10       44
11       47
12      242
13      467
14       51
15      233
16      243
17      252
18       58
19      146
20       54
21      134
22      142
23       34
24       19
25       14
26       36
27       58
28       79
29       21
30       58
31       19
32      160
33      423
34      318
35      150
36      240
37      108
38       67
39        5
40      135
41      224
42       55
43      253
44       22
45       94
46       39
47       18
48       62
49       62
50        0
51      128
52      211
53       10
54       58
55       78
56       40
57       44
58       31
59       47
60       25
61      216
62        8
63      427
64      193
65       11
66      364
67      174
68      119
69      117
70        4
71       38
72      550
73      170
74      157
75       14
76       16
77       36
78      260
79       51
80       28
81      244
82      209
83       35
84      112
85      117
86      133
87       80
88      201
89       80
90       23
91        8
92       31
93       11
94       52
95       51
96       15
97      331
98       21
99      102
100     150
101     101
102     296
103     167
104     110
105     570
106      65
107     117
108     162
109      13
110     180
111     128
112      11
113       0
114       0
115     180
116      16
117     134
118      94
119       8
120      87
121      28
122      76
123     158
124      81
125      36
126      26
127     129
128     191
129       0
130     266
131      23
132      43
133     118
134     218
135     179
136     216
137     203
138     148
139      89
140     266
141      25
142       6
143       6
144       2
145     178
146     292
147      24
148      20
149      39
150      58
151     175
152      89
153     199
154       0
155      13
156       5
157      24
158     320
159     477
160     446
161     275
162     169
163     293
164      81
165       8
166      10
167      22
168     160
169      96
170     146
171      64
172      22
173     107
174     100
175     218
176      48
177      18
178      23
179     249
180      69
181     257
182      26
183      13
184     137
185     106
186      84
187      19
188      13
189      63
190     175
191      18
192       0
193       1
194       5
195      39
196       7
197     147
198      79
199     142
200     132
201      24
202      45
203     261
204      72
205     233
206      29
207     243
208      40
209     110
210      66
211     236
212      21
213     276
214     108
215      26
216      73
217     148
218       7
219     306
220      30
221     109
222     399
223      99
224       3
225      37
226     283
227      43
228       0
229     151
230     463
231      44
232     107
233      27
234     204
235      14
236     147
237       4
238      16
239      10
240       4
241     176
242     243
243     166
244     177
245       4
246      26
247      15
248     132
249     110
       ...
7919      0
7920      1
7921      0
7922      1
7923      0
7924      0
7925      0
7926      2
7927      0
7928      3
7929      2
7930      3
7931      0
7932      1
7933      0
7934      0
7935      1
7936      1
7937      0
7938      0
7939      0
7940      0
7941      0
7942      0
7943      1
7944      0
7945      0
7946      0
7947      0
7948      0
7949      4
7950      0
7951      1
7952      0
7953      0
7954      0
7955      0
7956      1
7957      0
7958      1
7959      0
7960      0
7961      0
7962      1
7963      1
7964      0
7965      0
7966      0
7967      1
7968      0
7969      0
7970      1
7971      0
7972      1
7973      0
7974      2
7975      0
7976      2
7977      0
7978      0
7979      0
7980      0
7981      0
7982      0
7983      0
7984      1
7985      0
7986      1
7987      1
7988      0
7989      2
7990      0
7991      0
7992      1
7993      4
7994      0
7995      0
7996      0
7997      4
7998      1
7999      0
8000      0
8001      0
8002      2
8003      0
8004      0
8005      0
8006      0
8007      0
8008      0
8009      0
8010      0
8011      0
8012      0
8013      1
8014      0
8015      1
8016      0
8017      0
8018      0
8019      0
8020      1
8021      0
8022      0
8023      1
8024      0
8025      1
8026      0
8027      1
8028      0
8029      0
8030      0
8031      0
8032      0
8033      0
8034      0
8035      0
8036      0
8037      0
8038      0
8039      0
8040      0
8041      0
8042      0
8043      0
8044      0
8045      0
8046      0
8047      0
8048      3
8049      0
8050      0
8051      0
8052      0
8053      0
8054      0
8055      0
8056      0
8057      0
8058      0
8059      0
8060      0
8061      0
8062      0
8063      0
8064      0
8065      0
8066      0
8067      0
8068      0
8069      0
8070      0
8071      0
8072      0
8073      0
8074      0
8075      0
8076      0
8077      0
8078      0
8079      0
8080      0
8081      0
8082      0
8083      0
8084      0
8085      0
8086      0
8087      1
8088      0
8089      0
8090      0
8091      0
8092      0
8093      0
8094      0
8095      0
8096      0
8097      1
8098      0
8099      0
8100      0
8101      0
8102      0
8103      0
8104      0
8105      0
8106      0
8107      0
8108      0
8109      0
8110      0
8111      0
8112      0
8113      0
8114      0
8115      0
8116      0
8117      1
8118      0
8119      0
8120      0
8121      0
8122      0
8123      0
8124      0
8125      0
8126      0
8127      0
8128      0
8129      0
8130      1
8131      0
8132      0
8133      0
8134      0
8135      0
8136      0
8137      0
8138      0
8139      0
8140      0
8141      0
8142      0
8143      0
8144      0
8145      0
8146      0
8147      0
8148      0
8149      0
8150      0
8151      0
8152      0
8153      0
8154      0
8155      0
8156      0
8157      0
8158      0
8159      0
8160      0
8161      0
8162      0
8163      0
8164      0
8165      0
8166      0
8167      0
8168      0
Name: number_of_reviews, Length: 8169, dtype: int64